# Site settings
title: David Adamec
email: david@neruson.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm David. Welcome to my site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://neruson.com" # the base hostname & protocol for your site
twitter_username: neruson
github_username:  neruson

# Build settings
markdown: kramdown
